services:
  - type: web
    name: sql-mcp-server
    env: python3
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server_complete.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sql-mcp-db
          property: connectionString
      - key: API_KEY
        value: GenuinMiglioreAgenteDelMondo
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    
  - type: pserv
    name: sql-mcp-db
    env: postgresql
    region: frankfurt  
    plan: free
    databaseName: inventario_db
    databaseUser: inventario_user
